version: "3.9"

services:
    laravelapp:
        container_name: laravelapp
        image: laravel-app
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
